codecov:
  notify:
    wait_for_ci: false
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 99%
        threshold: 1%
    patch:
      default:
        target: 99%
        threshold: 1%

comment:
  require_changes: true
