codecov:
  notify:
    wait_for_ci: false
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 99%
        threshold: 1%
    patch:
      default:
        target: 99%
        threshold: 1%

comment:
  require_changes: true

flag_management:
  default_rules:
    statuses:
      - type: project
        target: 99%
        threshold: 1%
      - type: patch
        target: 99%
        threshold: 1%
  individual_flags:
    - name: ruby 2.7
      paths: [coverage-results/ruby-2.7*]
    - name: ruby 3.0
      paths: [coverage-results/ruby-3.0*]
    - name: ruby 3.1
      paths: [coverage-results/ruby-3.1*]
    - name: ruby 3.2
      paths: [coverage-results/ruby-3.2*]
    - name: ruby 3.3
      paths: [coverage-results/ruby-3.3*]
    - name: ruby 3.4
      paths: [coverage-results/ruby-3.4*]
