# frozen_string_literal: true

namespace :coverage do
  desc "Run coverage with spec"
  task :run do
    require "simplecov"
    require "rake/clean"
    # clean up previously generated report
    Rake::Cleaner.cleanup_files([SimpleCov.coverage_dir])

    Rake::Task[:spec].invoke(coverage: true)
  end

  desc "Collates coverage results generated by different test runners"
  task :report do
    coverage_dir = File.join(ENV.fetch("COV_DIR", "coverage"), "ruby-*")
    coverage_reports = Dir[File.join(coverage_dir, ".resultset.json")]

    raise <<~MSG if coverage_reports.empty?
      Coverage reports not found, searched in:
      #{Dir[coverage_dir].map { |dir| "  - #{dir}\n" }.join}
    MSG

    require "simplecov"
    SimpleCov.collate(coverage_reports) do
      coverage_dir "coverage"
    end
  end
end
