# frozen_string_literal: true

namespace :coverage do
  desc "Run coverage with spec"
  task :run do
    Rake::Task[:spec].invoke(coverage: true)
  end

  desc "Collates coverage results generated by different test runners"
  task :report do
    require "simplecov"
    SimpleCov.collate Dir["coverage-*/.resultset.json"] do
      coverage_dir "coverage"
    end
  end
end
