#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "rodiff/cli"

# set invoked_via_subcommand to ensure default command is used
Rodiff::CLI.start(ARGV, invoked_via_subcommand: true)
