#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "rodiff/executable"

begin
  verbose = ARGV.delete "--verbose"
  command = [Rodiff::Executable.resolve, *ARGV]
  puts "rodiff: #{command.inspect}" if verbose

  if Gem.win_platform?
    # use system rather than exec as exec inexplicably fails to find the executable on Windows
    # see related https://github.com/rubys/sprockets-esbuild/pull/4
    system(*command, exception: true)
  else
    exec(*command)
  end
rescue Rodiff::Executable::Error => e
  warn("ERROR: #{e.message}")
  exit 1
end
